src/videoservice/courses/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, LessonDetailView


app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<slug>', CourseDetailView.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>', LessonDetailView.as_view(), name='lesson-detail')
]

src/videoservice/memberships/urls.py
from django.urls import path
from .views import (
	MembershipSelectView, 
	PaymentView, 
	updateTransactions,
	profile_view,
	cancelSubscription)


app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactions, name='update-transactions'),
    path('profile/', profile_view, name='profile'),
   	path('cancel/', cancelSubscription, name='cancel')
]

src/videoservice/videoservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('memberships.urls', namespace='memberships')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('accounts/', include('allauth.urls')),  
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, documant_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, documant_root=settings.MEDIA_ROOT)

src/videoservice/courses/models.py
from django.db import models
from django.urls import reverse
from memberships.models import Membership

class Course(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	description = models.TextField()
	allowed_memberships = models.ManyToManyField(Membership)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:detail', kwargs={'slug':self.slug})

	@property
	def lessons(self):
		return self.lesson_set.all().order_by('position')
	

class Lesson(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
	position = models.IntegerField()
	video = models.FileField(upload_to="user_videos/", null=True)
	thumbnail = models.ImageField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:lesson-detail', 
			kwargs={
				'course_slug' : self.course.slug,
				'lesson_slug'  :self.slug
			})

src/videoservice/courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View
from memberships.models import UserMembership
from .models import Course

class CourseListView(ListView):
	model = Course

class CourseDetailView(DetailView):
	model = Course

class LessonDetailView(LoginRequiredMixin, View):

	def get(self, request, course_slug, lesson_slug, *args, **kwargs):

		course_qs = Course.objects.filter(slug=course_slug)
		if course_qs.exists():
			course = course_qs.first()

		lesson_qs = course.lessons.filter(slug=lesson_slug)
		if lesson_qs.exists():
			lesson = lesson_qs.first()

		user_membership = UserMembership.objects.filter(user=request.user).first()
		user_membership_type = user_membership.membership.membership_type
		course_allowed_mem_types = course.allowed_memberships.all()

		context = {
			'object'  : None
		}

		if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
			context = {'object' : lesson}


		return render(request, 'courses/lesson_detail.html', context)

src/videoservice/courses/templates/courses/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Django Video Membership</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://cdn.plyr.io/3.5.6/plyr.js"></script>
	<link rel="stylesheet" href="https://cdn.plyr.io/3.5.6/plyr.css" />
</head>
<body>

	{% include 'courses/messages.html' %}

	<div class="container">
		<ol class='breadcrumb'>
	        <li><a href="{% url 'memberships:profile' %}">Profile</a></li>
	        
	        {% block post_detail_link %}
	        {% endblock %}

	        {% if not request.user.is_authenticated %}
	        <li class='pull-right'><a href='/register'>Register</a></li>
	        <li class='pull-right'><a href='/login'>Login</a></li>
	        {% else %}
	        <li class='pull-right'><a href='/memberships'>Memberships</a></li>
	        {% endif %}
	    </ol>
	</div>

	{% block content %}
	{% endblock content %}

	<script
  	src="https://code.jquery.com/jquery-3.3.1.js"
  	integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  	crossorigin="anonymous"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

src/videoservice/courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block post_detail_link %}
	<li>{{object.title}}</li>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col">
			<h1>{{object.title}}</h1>
			<p>{{object.description}}</p>
			<ol>
				{% for lesson in object.lessons %}
					<li><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a></li>
				{% endfor %}
			</ol>

		</div>
	</div>
</div>
{% endblock %}

src/videoservice/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col">
				<h1>Course List</h1>
				{% for object in object_list %}
					<a href="{{ object.get_absolute_url }}">{{ object }}</a href="{{ object.get_absolute_url }}">
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

src/videoservice/courses/templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}

{% block post_detail_link %}
{% if object is not None %}
	<li><a class="nav-link text-white" href="{{ object.course.get_absolute_url }}">{{ object.course.title }}</a></li>
	<li>{{ object.title }}</li>
{% endif %}
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1>Lesson Details</h1>
			{% if object is not None %}
				<h3>{{ object.title }}</h3>
				<p>{{ object.description }}</p>

				<video poster="/path/to/poster.jpg" id="player" playsinline controls>
				    <source src="{{object.video}}" type="video/mp4" />
				    <source src="{{object.video}}" type="video/webm" />

				    <!-- Captions are optional -->
				    <track kind="captions" label="English captions" src="/path/to/captions.vtt" srclang="en" default />
				</video>
			{% else %}
				<h5>Upgrade membership</h5>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select' %}"><button class="btn btn-warning">Check out memberships</button></a>
				<hr>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

src/videoservice/courses/templates/courses/messages.html
{% if messages %}
 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>
	    <ul class="messages">
	    {% for message in messages %}
		    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
		    	{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
		    </li>
		    {% endfor %}
	    </ul>
    </div>
{% endif %}