src/videoservice/courses/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, LessonDetailView


app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<slug>', CourseDetailView.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>', LessonDetailView.as_view(), name='lesson-detail')
]

src/videoservice/memberships/urls.py
from django.urls import path
from .views import (
	MembershipSelectView, 
	PaymentView, 
	updateTransactions,
	profile_view,
	cancelSubscription)


app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactions, name='update-transactions'),
    path('profile/', profile_view, name='profile'),
   	path('cancel/', cancelSubscription, name='cancel')
]

src/videoservice/videoservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('memberships.urls', namespace='memberships')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('accounts/', include('allauth.urls')),  
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, documant_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, documant_root=settings.MEDIA_ROOT)

src/videoservice/courses/models.py
from django.db import models
from django.urls import reverse
from memberships.models import Membership

class Course(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	description = models.TextField()
	allowed_memberships = models.ManyToManyField(Membership)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:detail', kwargs={'slug':self.slug})

	@property
	def lessons(self):
		return self.lesson_set.all().order_by('position')
	

class Lesson(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
	position = models.IntegerField()
	video = models.FileField(upload_to="user_videos/", null=True)
	thumbnail = models.ImageField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:lesson-detail', 
			kwargs={
				'course_slug' : self.course.slug,
				'lesson_slug'  :self.slug
			})

src/videoservice/memberships/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from datetime import datetime
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
	('Enterprise', 'ent'),
	('Professional', 'pro'),
	('Free', 'free')
)

class Membership(models.Model):
	slug = models.SlugField()
	membership_type = models.CharField(
		choices=MEMBERSHIP_CHOICES,
		default='Free',
		max_length=30)
	price = models.IntegerField(default=15)
	stripe_plan_id  = models.CharField(max_length=40)

	def __str__(self):
		return self.membership_type


class UserMembership(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	stripe_customer_id  = models.CharField(max_length=40)
	membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.user.username


def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
	if created:
		UserMembership.objects.get_or_create(user=instance)

	user_membership, created = UserMembership.objects.get_or_create(user=instance)

	if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
		new_customer_id = stripe.Customer.create(email=instance.email)
		user_membership.stripe_customer_id = new_customer_id['id']
		user_membership.save()

post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)



class Subscription(models.Model):
	user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
	stripe_subscription_id  = models.CharField(max_length=40)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.user_membership.user.username

	@property
	def get_created_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.created)

	@property
	def get_next_billing_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.current_period_end)

src/videoservice/memberships/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView
from .models import Membership, UserMembership, Subscription
import stripe


def get_user_membership(request):
	user_membership_qs = UserMembership.objects.filter(user=request.user)
	if user_membership_qs.exists():
		return user_membership_qs.first()
	return None

def get_user_subscription(request):
	user_subscription_qs = Subscription.objects.filter(
			user_membership = get_user_membership(request))
	if user_subscription_qs.exists():
		user_subscription = user_subscription_qs.first()
		return user_subscription
	return None

def get_selected_membership(request):
	membership_type = request.session['selected_membership_type']
	selected_membership_qs = Membership.objects.filter(
				membership_type = membership_type)
	if selected_membership_qs.exists():
		return selected_membership_qs.first()
	return None

@login_required
def profile_view(request):
    user_membership = get_user_membership(request)
    user_subscription = get_user_subscription(request)
    context = {
        'user_membership' : user_membership,
        'user_subscription' : user_subscription
    }
    return render(request, 'memberships/profile.html', context)

class MembershipSelectView(LoginRequiredMixin, ListView):
	model = Membership

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(**kwargs)
		current_membership = get_user_membership(self.request)
		context['current_membership'] = str(current_membership.membership)
		return context

	def post(self, request, **kwargs):
		selected_membership_type = request.POST.get('membership_type')
		user_membership = get_user_membership(request)
		user_subscription = get_user_subscription(request)

		selected_membership_qs = Membership.objects.filter(
			membership_type=selected_membership_type)

		if selected_membership_qs.exists():
			selected_membership = selected_membership_qs.first()
			
		#validation

		if user_membership.membership == selected_membership:
			if user_subscription != None:
				messages.info(request, "You alreay ahve this membership \n Your next payment is due {}".format("get this from stripe"))
				return HttpResponseRedirect(request.META.GET('HTTP_REFERER'))

		
		# assign to the session
		request.session['selected_membership_type']	= selected_membership.membership_type
		return HttpResponseRedirect(reverse('memberships:payment'))

@login_required
def PaymentView(request):
    user_membership = get_user_membership(request)
    try:
        selected_membership = get_selected_membership(request)
    except:
        return redirect(reverse("memberships:select"))
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == "POST":
        try:
            token = request.POST['stripeToken']

            customer = stripe.Customer.retrieve(user_membership.stripe_customer_id)
            customer.source = token # 4242424242424242
            customer.save()

            subscription = stripe.Subscription.create(
                customer=user_membership.stripe_customer_id,
                items=[
                    { "plan": selected_membership.stripe_plan_id },
                ]
            )

            return redirect(reverse('memberships:update-transactions',
                                    kwargs={
                                        'subscription_id': subscription.id
                                    }))

        except:
            messages.info(request, "An error has occurred, investigate it in the console")

    context = {
        'publishKey': publishKey,
        'selected_membership': selected_membership
    }

    return render(request, "memberships/membership_payment.html", context)

@login_required
def updateTransactions(request, subscription_id):
	user_membership = get_user_membership(request)
	selected_membership = get_selected_membership(request)
	user_membership.membership = selected_membership
	user_membership.save()

	sub, created = Subscription.objects.get_or_create(user_membership=user_membership)
	sub.stripe_subscription_id = subscription_id
	sub.active = True
	sub.save()

	try:
		del request.session['selected_membership_type']
	except:
		pass

	messages.info(request, "Successfully created {} membership".format(selected_membership))
	return redirect(reverse('memberships:select'))

@login_required
def cancelSubscription(request):
	user_sub = get_user_subscription(request)

	if user_sub.active is False:
		messages.info(request, "You dont have an active membership")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
	sub.delete()

	user_sub.active = False
	user_sub.save()

	free_membership = Membership.objects.get(membership_type='Free')
	user_membership = get_user_membership(request)
	user_membership.membership = free_membership
	user_membership.save()

	messages.info(
	request, "Successfully cancelled membership. We have sent an email")
	# sending an email here

	return redirect(reverse('memberships:select'))

src/videoservice/memberships/templates/memberships/membership_list.html
{% extends 'courses/base.html' %}

{% block content %}
	<div class="container">
		<h1>Select a Membership</h1>
		<div class="row">
			{% for object in object_list %}
				<div class="col-sm-4 col-md-4">
					<h2>{{ object.membership_type }}</h2>
					<p>Price: ${{object.monthly_price}}<small>/month</small></p>
					<h4>Included Courses</h4>
					<ul>
						{% for course in object.course_set.all %}
							<li>{{course.title}}</li>
						{% endfor %}
					</ul>
					{% if object.membership_type  != 'Free' %}
					<form method="POST" action="{% url 'memberships:select' %}">
						{% csrf_token %}
						{% if object.membership_type != current_membership %}
							<button class="btn btn-warning">Select</button>
						{% else %}
							<small>This is your current membership plan</small>
						{% endif %}
						<input type="hidden" name="membership_type" value="{{object.membership_type}}">
					</form>
					{% endif %}
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock content %}

src/videoservice/memberships/templates/memberships/membership_payment.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">

    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-md-4">
                <h1>Payment</h1>
                <p>Selected membership: {{ selected_membership }}</p>
                <p>Price: <strong>${{ selected_membership.price }}</strong><small>/month</small></p>

                <button onclick="toggleDisplay();" class="btn btn-warning" style="width: 100%;">Checkout with a credit card</button>

                <div id="collapseStripe" class="wrapper">
                    <script src="https://js.stripe.com/v3/"></script>

                    <!-- can't do this -->
                    <!-- <script src="{% static 'js/stripeV3.js' %}"></script> -->

                    <form action="." method="post" id="payment-form">
                        {% csrf_token %}
                        <div class="form-row">
                            <label for="card-element">
                                Credit or debit card
                            </label>
                            <div id="card-element" class="StripeElement StripeElement--empty w-100 p-3">
                                <div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                                    <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame3" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-8a434729e4eb82355db4882974049278.html#style[base][color]=%2332325d&amp;style[base][lineHeight]=18px&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;features[noop]=false&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js%2Felements%2Fquickstart&amp;controllerId=__privateStripeController0" title="Secure payment input frame" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 18px;"></iframe>
                                    <input class="__PrivateStripeElement-input" aria-hidden="true" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                                    <input class="__PrivateStripeElement-safariInput" aria-hidden="true" tabindex="-1" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                                </div>
                            </div>

                            <!-- Used to display form errors. -->
                            <div id="card-errors" role="alert"></div>
                        </div>

                        <button>Submit Payment</button>
                    </form>

                </div>

            </div>

            <div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div>

        </div>
    </div>
    </div>

    <!-- script for the stripe form -->
    <script src="{% static 'js/checkout.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- script for toggling display of the form -->
    <script type="text/javascript">
        function toggleDisplay() {
            var x = document.getElementById("collapseStripe");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        };
    </script>

{% endblock content %}

src/videoservice/memberships/templates/memberships/profile.html
{% extends 'courses/base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-md-6">
				<h1>My Profile</h1>
				{% if user_subscription != None %}
					<h4>Current Membership : {{ user_membership.membership.membership_type }} <small>  since {{ user_subscription.get_created_date }}</small></h4>

					{% if user_subscription.active != False %}
						<p>Nexy payment due : {{ user_subscription.get_next_billing_date }}</p>
						<a href="{% url 'memberships:cancel' %}">Cancel current subscription</a>
					{% else %}
						<p>You don't have an active membership plan. Check them out here 
							<a href="{% url 'memberships:select' %}"></a>
						</p>
					{% endif %}

				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}